# Generated by Django 3.2.9 on 2021-12-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
