# Generated by Django 3.2.9 on 2021-12-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20211204_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Importance_levels',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
