# Generated by Django 3.2.9 on 2021-12-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20211204_1849'),
        ('main_app', '0010_note_photo'),
    ]

    operations = [
    ]
