# Generated by Django 3.2.9 on 2021-12-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='when',
            field=models.DateTimeField(verbose_name='Time Until'),
        ),
    ]
